### ISSUE TITLE
Running conda-pytorch from a secondary drive causes a linking issue

### ISSUE THREAD

**Issue by kurtamohler** [Quansight/conda-pytorch#1]
On the qgpu machines, I keep my pytorch repo checkouts in the `/work` directory, which is on a larger secondary hard drive. This causes an issue when conda-pytorch tries to (presumably) create hard links from pytorch nightly files in `/tmp` to the pytorch repo directory. Since it's not possible to create hard links between two different drives, it fails.

When I run `conda-pytorch dev` inside my pytorch checkout in `/work/kurtamohler/development/pytorch-cuda`, I get this error:

```
INFO:conda-pytorch:Checking out nightly PyTorch took 6.901 [s]
INFO:conda-pytorch:Moving nightly files into repo
Linking /tmp/tmp37q8i1vy/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so -> /work/kurtamohler/development/pytorch-conda/torch/_C.cpython-38-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "/home/kurtamohler/miniconda3/bin/conda-pytorch", line 11, in <module>
    load_entry_point('conda-pytorch==0.0.0', 'console_scripts', 'conda-pytorch')()
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/main.py", line 25, in main
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/main.py", line 17, in dev
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/develop.py", line 208, in install
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/tools.py", line 27, in wrapper
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/develop.py", line 198, in move_nightly_files
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/develop.py", line 184, in _link_files
  File "/home/kurtamohler/miniconda3/lib/python3.7/site-packages/conda_pytorch-0.0.0-py3.7.egg/conda_pytorch/develop.py", line 174, in _move_single
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp37q8i1vy/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so' -> '/work/kurtamohler/development/pytorch-conda/torch/_C.cpython-38-x86_64-linux-gnu.so'
```

**Comment by kurtamohler** [comment]
Would there be any issue with checking out the nightly pytorch directly into the repo, avoiding `/tmp`?

**Comment by kurtamohler** [comment]
Ah I see that on Windows, these files are being copied rather than linked. I'll make a PR to check if the target dir is on a different drive, and copy the files if so.

**Comment by scopatz** [comment]
If this ends up being a real issue, I can move the temp directory to the current PyTorch repo dir.  And that should fix it.  Also I just fixed an issue with relative paths not copying correctly
